import type { Metadata } from "next";
import { Poppins, Newsreader } from "next/font/google";
import dynamic from "next/dynamic";
import Footer from "@/components/Footer";
import "./globals.css";
import Navbar from "@/components/navbar";

const AdModal = dynamic(() => import("@/components/ad_modal"));

const poppins = Poppins({
  variable: "--font-poppins",
  style: ["normal", "italic"],
  display: "swap",
  fallback: ["system-ui", "sans-serif"],
  preload: true,
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const newsreader = Newsreader({
  variable: "--font-newsreader",
  style: ["normal", "italic"],
  display: "swap",
  fallback: ["serif"],
  preload: true,
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Harisiddhi Newa Suli",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${newsreader.variable} antialiased`}
      >
        {/*<AdModal />*/}
        <Navbar />
        <main className="min-h-screen">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
