import type { Metadata } from "next";
import { Poppins, Newsreader } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  style: ["normal", "italic"],
  display: "swap",
  fallback: ["system-ui", "sans-serif"],
  preload: true,
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const newsreader = Newsreader({
  variable: "--font-newsreader",
  style: ["normal", "italic"],
  display: "swap",
  fallback: ["serif"],
  preload: true,
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${newsreader.variable} antialiased`}
      >
        <main>{children}</main>
      </body>
    </html>
  );
}
